require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BreadStoresController do

  # This should return the minimal set of attributes required to create a valid
  # BreadStore. As you add validations to BreadStore, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString", "phone_number" => "124", "address" => "AAA"} }
  let(:invalid_attributes) { { "name" => "MyString", "phone_number" => "aaa", "address" => "AAA"} }

  let(:example1) { { "name" => "パン屋岡田", "phone_number" => "090-2548-6324", "address" => "神奈川県横浜市鶴見区下野谷町４－１５４－３２サンパレスミシマ４０１号"} }
  let(:example2) { { "name" => "ｵｶﾀﾞ", "phone_number" => "090-2548-632400000000000000", "address" => "〒270-0013ｻﾝﾊﾟﾚｽﾐｼﾏ"} }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BreadStoresController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all bread_stores as @bread_stores" do
      bread_store = BreadStore.create! valid_attributes
      get :index, {}, valid_session
      assigns(:bread_stores).should eq([bread_store])
    end
  end

  #describe "new check" do
  #  it "new時に失敗するかどうか" do
  #    bread_store = BreadStore.create! invalid_attributes
  #  end
  #end


  describe "GET show" do
    it "assigns the requested bread_store as @bread_store" do
      bread_store = BreadStore.create! valid_attributes
      get :show, {:id => bread_store.to_param}, valid_session
      assigns(:bread_store).should eq(bread_store)
    end
  end
=begin
  describe "GET new" do
    it "assigns a new bread_store as @bread_store" do
      get :new, {}, valid_session
      assigns(:bread_store).should be_a_new(BreadStore)
    end
  end

  describe "GET edit" do
    it "assigns the requested bread_store as @bread_store" do
      bread_store = BreadStore.create! valid_attributes
      get :edit, {:id => bread_store.to_param}, valid_session
      assigns(:bread_store).should eq(bread_store)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new BreadStore" do
        expect {
          post :create, {:bread_store => valid_attributes}, valid_session
        }.to change(BreadStore, :count).by(1)
      end

      it "assigns a newly created bread_store as @bread_store" do
        post :create, {:bread_store => valid_attributes}, valid_session
        assigns(:bread_store).should be_a(BreadStore)
        assigns(:bread_store).should be_persisted
      end

      it "redirects to the created bread_store" do
        post :create, {:bread_store => valid_attributes}, valid_session
        response.should redirect_to(BreadStore.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved bread_store as @bread_store" do
        # Trigger the behavior that occurs when invalid params are submitted
        BreadStore.any_instance.stub(:save).and_return(false)
        post :create, {:bread_store => { "name" => "invalid value" }}, valid_session
        assigns(:bread_store).should be_a_new(BreadStore)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        BreadStore.any_instance.stub(:save).and_return(false)
        post :create, {:bread_store => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested bread_store" do
        bread_store = BreadStore.create! valid_attributes
        # Assuming there are no other bread_stores in the database, this
        # specifies that the BreadStore created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        BreadStore.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => bread_store.to_param, :bread_store => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested bread_store as @bread_store" do
        bread_store = BreadStore.create! valid_attributes
        put :update, {:id => bread_store.to_param, :bread_store => valid_attributes}, valid_session
        assigns(:bread_store).should eq(bread_store)
      end

      it "redirects to the bread_store" do
        bread_store = BreadStore.create! valid_attributes
        put :update, {:id => bread_store.to_param, :bread_store => valid_attributes}, valid_session
        response.should redirect_to(bread_store)
      end
    end

    describe "with invalid params" do
      it "assigns the bread_store as @bread_store" do
        bread_store = BreadStore.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BreadStore.any_instance.stub(:save).and_return(false)
        put :update, {:id => bread_store.to_param, :bread_store => { "name" => "invalid value" }}, valid_session
        assigns(:bread_store).should eq(bread_store)
      end

      it "re-renders the 'edit' template" do
        bread_store = BreadStore.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BreadStore.any_instance.stub(:save).and_return(false)
        put :update, {:id => bread_store.to_param, :bread_store => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested bread_store" do
      bread_store = BreadStore.create! valid_attributes
      expect {
        delete :destroy, {:id => bread_store.to_param}, valid_session
      }.to change(BreadStore, :count).by(-1)
    end

    it "redirects to the bread_stores list" do
      bread_store = BreadStore.create! valid_attributes
      delete :destroy, {:id => bread_store.to_param}, valid_session
      response.should redirect_to(bread_stores_url)
    end
  end
=end
end
